# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tugboat_control/BoatStatus.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class BoatStatus(genpy.Message):
  _md5sum = "c456c1039b34e445f3d3bf38126f7305"
  _type = "tugboat_control/BoatStatus"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 ID # ID > 99 indicates ship
float64 x #x position in meters
float64 y #y position in meters
float64 theta #orientation in radians or degrees?
float32 PushingForce # Newton"""
  __slots__ = ['ID','x','y','theta','PushingForce']
  _slot_types = ['uint8','float64','float64','float64','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ID,x,y,theta,PushingForce

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BoatStatus, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.ID is None:
        self.ID = 0
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.theta is None:
        self.theta = 0.
      if self.PushingForce is None:
        self.PushingForce = 0.
    else:
      self.ID = 0
      self.x = 0.
      self.y = 0.
      self.theta = 0.
      self.PushingForce = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B3df().pack(_x.ID, _x.x, _x.y, _x.theta, _x.PushingForce))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 29
      (_x.ID, _x.x, _x.y, _x.theta, _x.PushingForce,) = _get_struct_B3df().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B3df().pack(_x.ID, _x.x, _x.y, _x.theta, _x.PushingForce))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 29
      (_x.ID, _x.x, _x.y, _x.theta, _x.PushingForce,) = _get_struct_B3df().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B3df = None
def _get_struct_B3df():
    global _struct_B3df
    if _struct_B3df is None:
        _struct_B3df = struct.Struct("<B3df")
    return _struct_B3df
