# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tugboat_control/ShipControlInput.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import tugboat_control.msg
import geometry_msgs.msg

class ShipControlInput(genpy.Message):
  _md5sum = "945e5ec50a8c1a88de62ff9741f9d15f"
  _type = "tugboat_control/ShipControlInput"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#What information is pertinent for controller??
tugboat_control/BoatPose ShipPose
tugboat_control/TugStatus[] TugStatus
================================================================================
MSG: tugboat_control/BoatPose
float64 timestamp
geometry_msgs/Pose2D[11] Pose
================================================================================
MSG: geometry_msgs/Pose2D
# This expresses a position and orientation on a 2D manifold.

float64 x
float64 y
float64 theta
================================================================================
MSG: tugboat_control/TugStatus
uint8[] ID # ID > 99 indicates ship
float64 x #x position in meters
float64 y #y position in meters
float64 theta #orientation in radians or degrees?
float32 PushingForce # Newton"""
  __slots__ = ['ShipPose','TugStatus']
  _slot_types = ['tugboat_control/BoatPose','tugboat_control/TugStatus[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ShipPose,TugStatus

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ShipControlInput, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.ShipPose is None:
        self.ShipPose = tugboat_control.msg.BoatPose()
      if self.TugStatus is None:
        self.TugStatus = []
    else:
      self.ShipPose = tugboat_control.msg.BoatPose()
      self.TugStatus = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_d().pack(self.ShipPose.timestamp))
      for val1 in self.ShipPose.Pose:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.theta))
      length = len(self.TugStatus)
      buff.write(_struct_I.pack(length))
      for val1 in self.TugStatus:
        _x = val1.ID
        length = len(_x)
        # - if encoded as a list instead, serialize as bytes instead of string
        if type(_x) in [list, tuple]:
          buff.write(struct.pack('<I%sB'%length, length, *_x))
        else:
          buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_get_struct_3df().pack(_x.x, _x.y, _x.theta, _x.PushingForce))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.ShipPose is None:
        self.ShipPose = tugboat_control.msg.BoatPose()
      if self.TugStatus is None:
        self.TugStatus = None
      end = 0
      start = end
      end += 8
      (self.ShipPose.timestamp,) = _get_struct_d().unpack(str[start:end])
      self.ShipPose.Pose = []
      for i in range(0, 11):
        val1 = geometry_msgs.msg.Pose2D()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _get_struct_3d().unpack(str[start:end])
        self.ShipPose.Pose.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.TugStatus = []
      for i in range(0, length):
        val1 = tugboat_control.msg.TugStatus()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        val1.ID = str[start:end]
        _x = val1
        start = end
        end += 28
        (_x.x, _x.y, _x.theta, _x.PushingForce,) = _get_struct_3df().unpack(str[start:end])
        self.TugStatus.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_get_struct_d().pack(self.ShipPose.timestamp))
      for val1 in self.ShipPose.Pose:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.theta))
      length = len(self.TugStatus)
      buff.write(_struct_I.pack(length))
      for val1 in self.TugStatus:
        _x = val1.ID
        length = len(_x)
        # - if encoded as a list instead, serialize as bytes instead of string
        if type(_x) in [list, tuple]:
          buff.write(struct.pack('<I%sB'%length, length, *_x))
        else:
          buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_get_struct_3df().pack(_x.x, _x.y, _x.theta, _x.PushingForce))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.ShipPose is None:
        self.ShipPose = tugboat_control.msg.BoatPose()
      if self.TugStatus is None:
        self.TugStatus = None
      end = 0
      start = end
      end += 8
      (self.ShipPose.timestamp,) = _get_struct_d().unpack(str[start:end])
      self.ShipPose.Pose = []
      for i in range(0, 11):
        val1 = geometry_msgs.msg.Pose2D()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _get_struct_3d().unpack(str[start:end])
        self.ShipPose.Pose.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.TugStatus = []
      for i in range(0, length):
        val1 = tugboat_control.msg.TugStatus()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        val1.ID = str[start:end]
        _x = val1
        start = end
        end += 28
        (_x.x, _x.y, _x.theta, _x.PushingForce,) = _get_struct_3df().unpack(str[start:end])
        self.TugStatus.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3df = None
def _get_struct_3df():
    global _struct_3df
    if _struct_3df is None:
        _struct_3df = struct.Struct("<3df")
    return _struct_3df
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
