(cl:defpackage tugboat_control-srv
  (:use )
  (:export
   "ADDONETUG"
   "<ADDONETUG-REQUEST>"
   "ADDONETUG-REQUEST"
   "<ADDONETUG-RESPONSE>"
   "ADDONETUG-RESPONSE"
   "REMOVEONETUG"
   "<REMOVEONETUG-REQUEST>"
   "REMOVEONETUG-REQUEST"
   "<REMOVEONETUG-RESPONSE>"
   "REMOVEONETUG-RESPONSE"
  ))

