(cl:defpackage tugboat_control-srv
  (:use )
  (:export
   "AVOIDSHIPCOLLISION"
   "<AVOIDSHIPCOLLISION-REQUEST>"
   "AVOIDSHIPCOLLISION-REQUEST"
   "<AVOIDSHIPCOLLISION-RESPONSE>"
   "AVOIDSHIPCOLLISION-RESPONSE"
   "WAYPOINTAVAILABLE"
   "<WAYPOINTAVAILABLE-REQUEST>"
   "WAYPOINTAVAILABLE-REQUEST"
   "<WAYPOINTAVAILABLE-RESPONSE>"
   "WAYPOINTAVAILABLE-RESPONSE"
   "ADDONETUG"
   "<ADDONETUG-REQUEST>"
   "ADDONETUG-REQUEST"
   "<ADDONETUG-RESPONSE>"
   "ADDONETUG-RESPONSE"
   "REMOVEONETUG"
   "<REMOVEONETUG-REQUEST>"
   "REMOVEONETUG-REQUEST"
   "<REMOVEONETUG-RESPONSE>"
   "REMOVEONETUG-RESPONSE"
  ))

