// Generated by gencpp from file tugboat_control/AvoidShipCollision.msg
// DO NOT EDIT!


#ifndef TUGBOAT_CONTROL_MESSAGE_AVOIDSHIPCOLLISION_H
#define TUGBOAT_CONTROL_MESSAGE_AVOIDSHIPCOLLISION_H

#include <ros/service_traits.h>


#include <tugboat_control/AvoidShipCollisionRequest.h>
#include <tugboat_control/AvoidShipCollisionResponse.h>


namespace tugboat_control
{

struct AvoidShipCollision
{

typedef AvoidShipCollisionRequest Request;
typedef AvoidShipCollisionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AvoidShipCollision
} // namespace tugboat_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tugboat_control::AvoidShipCollision > {
  static const char* value()
  {
    return "1d3ed13e2b52083674842ac5b19130cb";
  }

  static const char* value(const ::tugboat_control::AvoidShipCollision&) { return value(); }
};

template<>
struct DataType< ::tugboat_control::AvoidShipCollision > {
  static const char* value()
  {
    return "tugboat_control/AvoidShipCollision";
  }

  static const char* value(const ::tugboat_control::AvoidShipCollision&) { return value(); }
};


// service_traits::MD5Sum< ::tugboat_control::AvoidShipCollisionRequest> should match 
// service_traits::MD5Sum< ::tugboat_control::AvoidShipCollision > 
template<>
struct MD5Sum< ::tugboat_control::AvoidShipCollisionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tugboat_control::AvoidShipCollision >::value();
  }
  static const char* value(const ::tugboat_control::AvoidShipCollisionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tugboat_control::AvoidShipCollisionRequest> should match 
// service_traits::DataType< ::tugboat_control::AvoidShipCollision > 
template<>
struct DataType< ::tugboat_control::AvoidShipCollisionRequest>
{
  static const char* value()
  {
    return DataType< ::tugboat_control::AvoidShipCollision >::value();
  }
  static const char* value(const ::tugboat_control::AvoidShipCollisionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tugboat_control::AvoidShipCollisionResponse> should match 
// service_traits::MD5Sum< ::tugboat_control::AvoidShipCollision > 
template<>
struct MD5Sum< ::tugboat_control::AvoidShipCollisionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tugboat_control::AvoidShipCollision >::value();
  }
  static const char* value(const ::tugboat_control::AvoidShipCollisionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tugboat_control::AvoidShipCollisionResponse> should match 
// service_traits::DataType< ::tugboat_control::AvoidShipCollision > 
template<>
struct DataType< ::tugboat_control::AvoidShipCollisionResponse>
{
  static const char* value()
  {
    return DataType< ::tugboat_control::AvoidShipCollision >::value();
  }
  static const char* value(const ::tugboat_control::AvoidShipCollisionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUGBOAT_CONTROL_MESSAGE_AVOIDSHIPCOLLISION_H
