// Generated by gencpp from file tugboat_control/AvoidShipCollisionRequest.msg
// DO NOT EDIT!


#ifndef TUGBOAT_CONTROL_MESSAGE_AVOIDSHIPCOLLISIONREQUEST_H
#define TUGBOAT_CONTROL_MESSAGE_AVOIDSHIPCOLLISIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tugboat_control/Waypoint.h>
#include <tugboat_control/Waypoint.h>

namespace tugboat_control
{
template <class ContainerAllocator>
struct AvoidShipCollisionRequest_
{
  typedef AvoidShipCollisionRequest_<ContainerAllocator> Type;

  AvoidShipCollisionRequest_()
    : from()
    , to()  {
    }
  AvoidShipCollisionRequest_(const ContainerAllocator& _alloc)
    : from(_alloc)
    , to(_alloc)  {
  (void)_alloc;
    }



   typedef  ::tugboat_control::Waypoint_<ContainerAllocator>  _from_type;
  _from_type from;

   typedef  ::tugboat_control::Waypoint_<ContainerAllocator>  _to_type;
  _to_type to;




  typedef boost::shared_ptr< ::tugboat_control::AvoidShipCollisionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tugboat_control::AvoidShipCollisionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AvoidShipCollisionRequest_

typedef ::tugboat_control::AvoidShipCollisionRequest_<std::allocator<void> > AvoidShipCollisionRequest;

typedef boost::shared_ptr< ::tugboat_control::AvoidShipCollisionRequest > AvoidShipCollisionRequestPtr;
typedef boost::shared_ptr< ::tugboat_control::AvoidShipCollisionRequest const> AvoidShipCollisionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tugboat_control::AvoidShipCollisionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tugboat_control::AvoidShipCollisionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tugboat_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'tugboat_control': ['/home/sondre/catkin_ws/src/tugboat_control/msg', '/home/sondre/catkin_ws/src/tugboat_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tugboat_control::AvoidShipCollisionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tugboat_control::AvoidShipCollisionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tugboat_control::AvoidShipCollisionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tugboat_control::AvoidShipCollisionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tugboat_control::AvoidShipCollisionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tugboat_control::AvoidShipCollisionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tugboat_control::AvoidShipCollisionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7fb7db3213c959c641065ea924ef61a5";
  }

  static const char* value(const ::tugboat_control::AvoidShipCollisionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7fb7db3213c959c6ULL;
  static const uint64_t static_value2 = 0x41065ea924ef61a5ULL;
};

template<class ContainerAllocator>
struct DataType< ::tugboat_control::AvoidShipCollisionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tugboat_control/AvoidShipCollisionRequest";
  }

  static const char* value(const ::tugboat_control::AvoidShipCollisionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tugboat_control::AvoidShipCollisionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Waypoint from\n\
Waypoint to\n\
\n\
================================================================================\n\
MSG: tugboat_control/Waypoint\n\
uint8 ID\n\
float64 x #	x position in meters\n\
float64 y #	y position in meters\n\
float64 v #	Velocity in m/s\n\
float64 o #	Orientation in +- pi radians from x-axis, for ship. Set outside scope to ignore Orientation\n\
";
  }

  static const char* value(const ::tugboat_control::AvoidShipCollisionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tugboat_control::AvoidShipCollisionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.from);
      stream.next(m.to);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AvoidShipCollisionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tugboat_control::AvoidShipCollisionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tugboat_control::AvoidShipCollisionRequest_<ContainerAllocator>& v)
  {
    s << indent << "from: ";
    s << std::endl;
    Printer< ::tugboat_control::Waypoint_<ContainerAllocator> >::stream(s, indent + "  ", v.from);
    s << indent << "to: ";
    s << std::endl;
    Printer< ::tugboat_control::Waypoint_<ContainerAllocator> >::stream(s, indent + "  ", v.to);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUGBOAT_CONTROL_MESSAGE_AVOIDSHIPCOLLISIONREQUEST_H
