// Generated by gencpp from file tugboat_control/AvoidShipCollisionResponse.msg
// DO NOT EDIT!


#ifndef TUGBOAT_CONTROL_MESSAGE_AVOIDSHIPCOLLISIONRESPONSE_H
#define TUGBOAT_CONTROL_MESSAGE_AVOIDSHIPCOLLISIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tugboat_control/Waypoint.h>

namespace tugboat_control
{
template <class ContainerAllocator>
struct AvoidShipCollisionResponse_
{
  typedef AvoidShipCollisionResponse_<ContainerAllocator> Type;

  AvoidShipCollisionResponse_()
    : path()  {
    }
  AvoidShipCollisionResponse_(const ContainerAllocator& _alloc)
    : path(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::tugboat_control::Waypoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::tugboat_control::Waypoint_<ContainerAllocator> >::other >  _path_type;
  _path_type path;




  typedef boost::shared_ptr< ::tugboat_control::AvoidShipCollisionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tugboat_control::AvoidShipCollisionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AvoidShipCollisionResponse_

typedef ::tugboat_control::AvoidShipCollisionResponse_<std::allocator<void> > AvoidShipCollisionResponse;

typedef boost::shared_ptr< ::tugboat_control::AvoidShipCollisionResponse > AvoidShipCollisionResponsePtr;
typedef boost::shared_ptr< ::tugboat_control::AvoidShipCollisionResponse const> AvoidShipCollisionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tugboat_control::AvoidShipCollisionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tugboat_control::AvoidShipCollisionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tugboat_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'tugboat_control': ['/home/sondre/catkin_ws/src/tugboat_control/msg', '/home/sondre/catkin_ws/src/tugboat_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tugboat_control::AvoidShipCollisionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tugboat_control::AvoidShipCollisionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tugboat_control::AvoidShipCollisionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tugboat_control::AvoidShipCollisionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tugboat_control::AvoidShipCollisionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tugboat_control::AvoidShipCollisionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tugboat_control::AvoidShipCollisionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "05c4b7b31d8093582857272e1de3c70c";
  }

  static const char* value(const ::tugboat_control::AvoidShipCollisionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x05c4b7b31d809358ULL;
  static const uint64_t static_value2 = 0x2857272e1de3c70cULL;
};

template<class ContainerAllocator>
struct DataType< ::tugboat_control::AvoidShipCollisionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tugboat_control/AvoidShipCollisionResponse";
  }

  static const char* value(const ::tugboat_control::AvoidShipCollisionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tugboat_control::AvoidShipCollisionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Waypoint[] path\n\
\n\
================================================================================\n\
MSG: tugboat_control/Waypoint\n\
uint8 ID\n\
float64 x #	x position in meters\n\
float64 y #	y position in meters\n\
float64 v #	Velocity in m/s\n\
float64 o #	Orientation in +- pi radians from x-axis, for ship. Set outside scope to ignore Orientation\n\
";
  }

  static const char* value(const ::tugboat_control::AvoidShipCollisionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tugboat_control::AvoidShipCollisionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AvoidShipCollisionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tugboat_control::AvoidShipCollisionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tugboat_control::AvoidShipCollisionResponse_<ContainerAllocator>& v)
  {
    s << indent << "path[]" << std::endl;
    for (size_t i = 0; i < v.path.size(); ++i)
    {
      s << indent << "  path[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tugboat_control::Waypoint_<ContainerAllocator> >::stream(s, indent + "    ", v.path[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUGBOAT_CONTROL_MESSAGE_AVOIDSHIPCOLLISIONRESPONSE_H
