// Generated by gencpp from file tugboat_control/BoatPose.msg
// DO NOT EDIT!


#ifndef TUGBOAT_CONTROL_MESSAGE_BOATPOSE_H
#define TUGBOAT_CONTROL_MESSAGE_BOATPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace tugboat_control
{
template <class ContainerAllocator>
struct BoatPose_
{
  typedef BoatPose_<ContainerAllocator> Type;

  BoatPose_()
    : timestamp(0.0)
    , Pose()  {
    }
  BoatPose_(const ContainerAllocator& _alloc)
    : timestamp(0.0)
    , Pose()  {
  (void)_alloc;
      Pose.assign( ::geometry_msgs::Pose2D_<ContainerAllocator> (_alloc));
  }



   typedef double _timestamp_type;
  _timestamp_type timestamp;

   typedef boost::array< ::geometry_msgs::Pose2D_<ContainerAllocator> , 11>  _Pose_type;
  _Pose_type Pose;




  typedef boost::shared_ptr< ::tugboat_control::BoatPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tugboat_control::BoatPose_<ContainerAllocator> const> ConstPtr;

}; // struct BoatPose_

typedef ::tugboat_control::BoatPose_<std::allocator<void> > BoatPose;

typedef boost::shared_ptr< ::tugboat_control::BoatPose > BoatPosePtr;
typedef boost::shared_ptr< ::tugboat_control::BoatPose const> BoatPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tugboat_control::BoatPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tugboat_control::BoatPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tugboat_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'tugboat_control': ['/home/sondre/catkin_ws/src/tugboat_control/msg', '/home/sondre/catkin_ws/src/tugboat_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tugboat_control::BoatPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tugboat_control::BoatPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tugboat_control::BoatPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tugboat_control::BoatPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tugboat_control::BoatPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tugboat_control::BoatPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tugboat_control::BoatPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fac719579a6887c70b1bfc580630888c";
  }

  static const char* value(const ::tugboat_control::BoatPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfac719579a6887c7ULL;
  static const uint64_t static_value2 = 0x0b1bfc580630888cULL;
};

template<class ContainerAllocator>
struct DataType< ::tugboat_control::BoatPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tugboat_control/BoatPose";
  }

  static const char* value(const ::tugboat_control::BoatPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tugboat_control::BoatPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 timestamp\n\
geometry_msgs/Pose2D[11] Pose\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::tugboat_control::BoatPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tugboat_control::BoatPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.Pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct BoatPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tugboat_control::BoatPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tugboat_control::BoatPose_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
    s << indent << "Pose[]" << std::endl;
    for (size_t i = 0; i < v.Pose.size(); ++i)
    {
      s << indent << "  Pose[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.Pose[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUGBOAT_CONTROL_MESSAGE_BOATPOSE_H
