// Generated by gencpp from file tugboat_control/BoatPose.msg
// DO NOT EDIT!


#ifndef TUGBOAT_CONTROL_MESSAGE_BOATPOSE_H
#define TUGBOAT_CONTROL_MESSAGE_BOATPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tugboat_control
{
template <class ContainerAllocator>
struct BoatPose_
{
  typedef BoatPose_<ContainerAllocator> Type;

  BoatPose_()
    : ID(0)
    , x(0.0)
    , y(0.0)
    , o(0.0)  {
    }
  BoatPose_(const ContainerAllocator& _alloc)
    : ID(0)
    , x(0.0)
    , y(0.0)
    , o(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _ID_type;
  _ID_type ID;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _o_type;
  _o_type o;




  typedef boost::shared_ptr< ::tugboat_control::BoatPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tugboat_control::BoatPose_<ContainerAllocator> const> ConstPtr;

}; // struct BoatPose_

typedef ::tugboat_control::BoatPose_<std::allocator<void> > BoatPose;

typedef boost::shared_ptr< ::tugboat_control::BoatPose > BoatPosePtr;
typedef boost::shared_ptr< ::tugboat_control::BoatPose const> BoatPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tugboat_control::BoatPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tugboat_control::BoatPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tugboat_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'tugboat_control': ['/home/sondre/catkin_ws/src/tugboat_control/msg', '/home/sondre/catkin_ws/src/tugboat_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tugboat_control::BoatPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tugboat_control::BoatPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tugboat_control::BoatPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tugboat_control::BoatPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tugboat_control::BoatPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tugboat_control::BoatPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tugboat_control::BoatPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e95f3e67135784b4229f3c4a980afa6c";
  }

  static const char* value(const ::tugboat_control::BoatPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe95f3e67135784b4ULL;
  static const uint64_t static_value2 = 0x229f3c4a980afa6cULL;
};

template<class ContainerAllocator>
struct DataType< ::tugboat_control::BoatPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tugboat_control/BoatPose";
  }

  static const char* value(const ::tugboat_control::BoatPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tugboat_control::BoatPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 ID # ID\n\
float64 x #x position in meters\n\
float64 y #y position in meters\n\
float64 o #orientation in +-pi radians from x-axis\n\
";
  }

  static const char* value(const ::tugboat_control::BoatPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tugboat_control::BoatPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ID);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.o);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoatPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tugboat_control::BoatPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tugboat_control::BoatPose_<ContainerAllocator>& v)
  {
    s << indent << "ID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ID);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "o: ";
    Printer<double>::stream(s, indent + "  ", v.o);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUGBOAT_CONTROL_MESSAGE_BOATPOSE_H
