// Generated by gencpp from file tugboat_control/removeOneTug.msg
// DO NOT EDIT!


#ifndef TUGBOAT_CONTROL_MESSAGE_REMOVEONETUG_H
#define TUGBOAT_CONTROL_MESSAGE_REMOVEONETUG_H

#include <ros/service_traits.h>


#include <tugboat_control/removeOneTugRequest.h>
#include <tugboat_control/removeOneTugResponse.h>


namespace tugboat_control
{

struct removeOneTug
{

typedef removeOneTugRequest Request;
typedef removeOneTugResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct removeOneTug
} // namespace tugboat_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tugboat_control::removeOneTug > {
  static const char* value()
  {
    return "4ac1f338ecfa845186d806d49892dc3b";
  }

  static const char* value(const ::tugboat_control::removeOneTug&) { return value(); }
};

template<>
struct DataType< ::tugboat_control::removeOneTug > {
  static const char* value()
  {
    return "tugboat_control/removeOneTug";
  }

  static const char* value(const ::tugboat_control::removeOneTug&) { return value(); }
};


// service_traits::MD5Sum< ::tugboat_control::removeOneTugRequest> should match 
// service_traits::MD5Sum< ::tugboat_control::removeOneTug > 
template<>
struct MD5Sum< ::tugboat_control::removeOneTugRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tugboat_control::removeOneTug >::value();
  }
  static const char* value(const ::tugboat_control::removeOneTugRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tugboat_control::removeOneTugRequest> should match 
// service_traits::DataType< ::tugboat_control::removeOneTug > 
template<>
struct DataType< ::tugboat_control::removeOneTugRequest>
{
  static const char* value()
  {
    return DataType< ::tugboat_control::removeOneTug >::value();
  }
  static const char* value(const ::tugboat_control::removeOneTugRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tugboat_control::removeOneTugResponse> should match 
// service_traits::MD5Sum< ::tugboat_control::removeOneTug > 
template<>
struct MD5Sum< ::tugboat_control::removeOneTugResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tugboat_control::removeOneTug >::value();
  }
  static const char* value(const ::tugboat_control::removeOneTugResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tugboat_control::removeOneTugResponse> should match 
// service_traits::DataType< ::tugboat_control::removeOneTug > 
template<>
struct DataType< ::tugboat_control::removeOneTugResponse>
{
  static const char* value()
  {
    return DataType< ::tugboat_control::removeOneTug >::value();
  }
  static const char* value(const ::tugboat_control::removeOneTugResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUGBOAT_CONTROL_MESSAGE_REMOVEONETUG_H
