// Generated by gencpp from file tugboat_control/removeOneTugResponse.msg
// DO NOT EDIT!


#ifndef TUGBOAT_CONTROL_MESSAGE_REMOVEONETUGRESPONSE_H
#define TUGBOAT_CONTROL_MESSAGE_REMOVEONETUGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tugboat_control
{
template <class ContainerAllocator>
struct removeOneTugResponse_
{
  typedef removeOneTugResponse_<ContainerAllocator> Type;

  removeOneTugResponse_()
    : ID(0)  {
    }
  removeOneTugResponse_(const ContainerAllocator& _alloc)
    : ID(0)  {
  (void)_alloc;
    }



   typedef uint8_t _ID_type;
  _ID_type ID;




  typedef boost::shared_ptr< ::tugboat_control::removeOneTugResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tugboat_control::removeOneTugResponse_<ContainerAllocator> const> ConstPtr;

}; // struct removeOneTugResponse_

typedef ::tugboat_control::removeOneTugResponse_<std::allocator<void> > removeOneTugResponse;

typedef boost::shared_ptr< ::tugboat_control::removeOneTugResponse > removeOneTugResponsePtr;
typedef boost::shared_ptr< ::tugboat_control::removeOneTugResponse const> removeOneTugResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tugboat_control::removeOneTugResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tugboat_control::removeOneTugResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tugboat_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'tugboat_control': ['/home/sondre/catkin_ws/src/tugboat_control/msg', '/home/sondre/catkin_ws/src/tugboat_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tugboat_control::removeOneTugResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tugboat_control::removeOneTugResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tugboat_control::removeOneTugResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tugboat_control::removeOneTugResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tugboat_control::removeOneTugResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tugboat_control::removeOneTugResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tugboat_control::removeOneTugResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4ac1f338ecfa845186d806d49892dc3b";
  }

  static const char* value(const ::tugboat_control::removeOneTugResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4ac1f338ecfa8451ULL;
  static const uint64_t static_value2 = 0x86d806d49892dc3bULL;
};

template<class ContainerAllocator>
struct DataType< ::tugboat_control::removeOneTugResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tugboat_control/removeOneTugResponse";
  }

  static const char* value(const ::tugboat_control::removeOneTugResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tugboat_control::removeOneTugResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 ID\n\
";
  }

  static const char* value(const ::tugboat_control::removeOneTugResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tugboat_control::removeOneTugResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct removeOneTugResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tugboat_control::removeOneTugResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tugboat_control::removeOneTugResponse_<ContainerAllocator>& v)
  {
    s << indent << "ID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUGBOAT_CONTROL_MESSAGE_REMOVEONETUGRESPONSE_H
