// Generated by gencpp from file tugboat_control/ThrustCommand.msg
// DO NOT EDIT!


#ifndef TUGBOAT_CONTROL_MESSAGE_THRUSTCOMMAND_H
#define TUGBOAT_CONTROL_MESSAGE_THRUSTCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tugboat_control
{
template <class ContainerAllocator>
struct ThrustCommand_
{
  typedef ThrustCommand_<ContainerAllocator> Type;

  ThrustCommand_()
    : ID(0)
    , thrust(0)
    , cwturn(0)  {
    }
  ThrustCommand_(const ContainerAllocator& _alloc)
    : ID(0)
    , thrust(0)
    , cwturn(0)  {
  (void)_alloc;
    }



   typedef uint8_t _ID_type;
  _ID_type ID;

   typedef int8_t _thrust_type;
  _thrust_type thrust;

   typedef int8_t _cwturn_type;
  _cwturn_type cwturn;




  typedef boost::shared_ptr< ::tugboat_control::ThrustCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tugboat_control::ThrustCommand_<ContainerAllocator> const> ConstPtr;

}; // struct ThrustCommand_

typedef ::tugboat_control::ThrustCommand_<std::allocator<void> > ThrustCommand;

typedef boost::shared_ptr< ::tugboat_control::ThrustCommand > ThrustCommandPtr;
typedef boost::shared_ptr< ::tugboat_control::ThrustCommand const> ThrustCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tugboat_control::ThrustCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tugboat_control::ThrustCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tugboat_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'tugboat_control': ['/home/sondre/catkin_ws/src/tugboat_control/msg', '/home/sondre/catkin_ws/src/tugboat_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tugboat_control::ThrustCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tugboat_control::ThrustCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tugboat_control::ThrustCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tugboat_control::ThrustCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tugboat_control::ThrustCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tugboat_control::ThrustCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tugboat_control::ThrustCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb36a969d5d22c5ec8c64a8469c7e207";
  }

  static const char* value(const ::tugboat_control::ThrustCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb36a969d5d22c5eULL;
  static const uint64_t static_value2 = 0xc8c64a8469c7e207ULL;
};

template<class ContainerAllocator>
struct DataType< ::tugboat_control::ThrustCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tugboat_control/ThrustCommand";
  }

  static const char* value(const ::tugboat_control::ThrustCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tugboat_control::ThrustCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# To Arduino\n\
uint8 ID\n\
int8 thrust # In % + 100\n\
int8 cwturn # In % + 100\n\
";
  }

  static const char* value(const ::tugboat_control::ThrustCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tugboat_control::ThrustCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ID);
      stream.next(m.thrust);
      stream.next(m.cwturn);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ThrustCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tugboat_control::ThrustCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tugboat_control::ThrustCommand_<ContainerAllocator>& v)
  {
    s << indent << "ID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ID);
    s << indent << "thrust: ";
    Printer<int8_t>::stream(s, indent + "  ", v.thrust);
    s << indent << "cwturn: ";
    Printer<int8_t>::stream(s, indent + "  ", v.cwturn);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUGBOAT_CONTROL_MESSAGE_THRUSTCOMMAND_H
