// Generated by gencpp from file tugboat_control/TugControlCommand.msg
// DO NOT EDIT!


#ifndef TUGBOAT_CONTROL_MESSAGE_TUGCONTROLCOMMAND_H
#define TUGBOAT_CONTROL_MESSAGE_TUGCONTROLCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tugboat_control
{
template <class ContainerAllocator>
struct TugControlCommand_
{
  typedef TugControlCommand_<ContainerAllocator> Type;

  TugControlCommand_()
    : orientation(0.0)
    , pushingForce(0.0)  {
    }
  TugControlCommand_(const ContainerAllocator& _alloc)
    : orientation(0.0)
    , pushingForce(0.0)  {
  (void)_alloc;
    }



   typedef float _orientation_type;
  _orientation_type orientation;

   typedef float _pushingForce_type;
  _pushingForce_type pushingForce;




  typedef boost::shared_ptr< ::tugboat_control::TugControlCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tugboat_control::TugControlCommand_<ContainerAllocator> const> ConstPtr;

}; // struct TugControlCommand_

typedef ::tugboat_control::TugControlCommand_<std::allocator<void> > TugControlCommand;

typedef boost::shared_ptr< ::tugboat_control::TugControlCommand > TugControlCommandPtr;
typedef boost::shared_ptr< ::tugboat_control::TugControlCommand const> TugControlCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tugboat_control::TugControlCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tugboat_control::TugControlCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tugboat_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'tugboat_control': ['/home/sondre/catkin_ws/src/tugboat_control/msg', '/home/sondre/catkin_ws/src/tugboat_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tugboat_control::TugControlCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tugboat_control::TugControlCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tugboat_control::TugControlCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tugboat_control::TugControlCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tugboat_control::TugControlCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tugboat_control::TugControlCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tugboat_control::TugControlCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "38391dab0ab53d38a3bbd7116ff3b3f9";
  }

  static const char* value(const ::tugboat_control::TugControlCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x38391dab0ab53d38ULL;
  static const uint64_t static_value2 = 0xa3bbd7116ff3b3f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::tugboat_control::TugControlCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tugboat_control/TugControlCommand";
  }

  static const char* value(const ::tugboat_control::TugControlCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tugboat_control::TugControlCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 orientation\n\
float32 pushingForce\n\
";
  }

  static const char* value(const ::tugboat_control::TugControlCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tugboat_control::TugControlCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.orientation);
      stream.next(m.pushingForce);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct TugControlCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tugboat_control::TugControlCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tugboat_control::TugControlCommand_<ContainerAllocator>& v)
  {
    s << indent << "orientation: ";
    Printer<float>::stream(s, indent + "  ", v.orientation);
    s << indent << "pushingForce: ";
    Printer<float>::stream(s, indent + "  ", v.pushingForce);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUGBOAT_CONTROL_MESSAGE_TUGCONTROLCOMMAND_H
