// Generated by gencpp from file tugboat_control/TugSetpoints.msg
// DO NOT EDIT!


#ifndef TUGBOAT_CONTROL_MESSAGE_TUGSETPOINTS_H
#define TUGBOAT_CONTROL_MESSAGE_TUGSETPOINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tugboat_control
{
template <class ContainerAllocator>
struct TugSetpoints_
{
  typedef TugSetpoints_<ContainerAllocator> Type;

  TugSetpoints_()
    : ID(0)
    , orientation(0.0)
    , pushingForce(0.0)  {
    }
  TugSetpoints_(const ContainerAllocator& _alloc)
    : ID(0)
    , orientation(0.0)
    , pushingForce(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _ID_type;
  _ID_type ID;

   typedef double _orientation_type;
  _orientation_type orientation;

   typedef double _pushingForce_type;
  _pushingForce_type pushingForce;




  typedef boost::shared_ptr< ::tugboat_control::TugSetpoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tugboat_control::TugSetpoints_<ContainerAllocator> const> ConstPtr;

}; // struct TugSetpoints_

typedef ::tugboat_control::TugSetpoints_<std::allocator<void> > TugSetpoints;

typedef boost::shared_ptr< ::tugboat_control::TugSetpoints > TugSetpointsPtr;
typedef boost::shared_ptr< ::tugboat_control::TugSetpoints const> TugSetpointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tugboat_control::TugSetpoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tugboat_control::TugSetpoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tugboat_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'tugboat_control': ['/home/sondre/catkin_ws/src/tugboat_control/msg', '/home/sondre/catkin_ws/src/tugboat_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tugboat_control::TugSetpoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tugboat_control::TugSetpoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tugboat_control::TugSetpoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tugboat_control::TugSetpoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tugboat_control::TugSetpoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tugboat_control::TugSetpoints_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tugboat_control::TugSetpoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b1a644af72e0374fc50096b433f3946";
  }

  static const char* value(const ::tugboat_control::TugSetpoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b1a644af72e0374ULL;
  static const uint64_t static_value2 = 0xfc50096b433f3946ULL;
};

template<class ContainerAllocator>
struct DataType< ::tugboat_control::TugSetpoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tugboat_control/TugSetpoints";
  }

  static const char* value(const ::tugboat_control::TugSetpoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tugboat_control::TugSetpoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 ID\n\
float64 orientation\n\
float64 pushingForce\n\
";
  }

  static const char* value(const ::tugboat_control::TugSetpoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tugboat_control::TugSetpoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ID);
      stream.next(m.orientation);
      stream.next(m.pushingForce);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct TugSetpoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tugboat_control::TugSetpoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tugboat_control::TugSetpoints_<ContainerAllocator>& v)
  {
    s << indent << "ID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ID);
    s << indent << "orientation: ";
    Printer<double>::stream(s, indent + "  ", v.orientation);
    s << indent << "pushingForce: ";
    Printer<double>::stream(s, indent + "  ", v.pushingForce);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUGBOAT_CONTROL_MESSAGE_TUGSETPOINTS_H
