// Generated by gencpp from file tugboat_control/TugWaypoint.msg
// DO NOT EDIT!


#ifndef TUGBOAT_CONTROL_MESSAGE_TUGWAYPOINT_H
#define TUGBOAT_CONTROL_MESSAGE_TUGWAYPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tugboat_control
{
template <class ContainerAllocator>
struct TugWaypoint_
{
  typedef TugWaypoint_<ContainerAllocator> Type;

  TugWaypoint_()
    : xPos(0.0)
    , yPos(0.0)
    , orientation(0.0)  {
    }
  TugWaypoint_(const ContainerAllocator& _alloc)
    : xPos(0.0)
    , yPos(0.0)
    , orientation(0.0)  {
  (void)_alloc;
    }



   typedef double _xPos_type;
  _xPos_type xPos;

   typedef double _yPos_type;
  _yPos_type yPos;

   typedef double _orientation_type;
  _orientation_type orientation;




  typedef boost::shared_ptr< ::tugboat_control::TugWaypoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tugboat_control::TugWaypoint_<ContainerAllocator> const> ConstPtr;

}; // struct TugWaypoint_

typedef ::tugboat_control::TugWaypoint_<std::allocator<void> > TugWaypoint;

typedef boost::shared_ptr< ::tugboat_control::TugWaypoint > TugWaypointPtr;
typedef boost::shared_ptr< ::tugboat_control::TugWaypoint const> TugWaypointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tugboat_control::TugWaypoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tugboat_control::TugWaypoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tugboat_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'tugboat_control': ['/home/sondre/catkin_ws/src/tugboat_control/msg', '/home/sondre/catkin_ws/src/tugboat_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tugboat_control::TugWaypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tugboat_control::TugWaypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tugboat_control::TugWaypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tugboat_control::TugWaypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tugboat_control::TugWaypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tugboat_control::TugWaypoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tugboat_control::TugWaypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "12dcab14506cdf2d1ef5fd11bde47896";
  }

  static const char* value(const ::tugboat_control::TugWaypoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x12dcab14506cdf2dULL;
  static const uint64_t static_value2 = 0x1ef5fd11bde47896ULL;
};

template<class ContainerAllocator>
struct DataType< ::tugboat_control::TugWaypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tugboat_control/TugWaypoint";
  }

  static const char* value(const ::tugboat_control::TugWaypoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tugboat_control::TugWaypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 xPos\n\
float64 yPos\n\
float64 orientation \n\
#What more do you want?\n\
";
  }

  static const char* value(const ::tugboat_control::TugWaypoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tugboat_control::TugWaypoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xPos);
      stream.next(m.yPos);
      stream.next(m.orientation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct TugWaypoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tugboat_control::TugWaypoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tugboat_control::TugWaypoint_<ContainerAllocator>& v)
  {
    s << indent << "xPos: ";
    Printer<double>::stream(s, indent + "  ", v.xPos);
    s << indent << "yPos: ";
    Printer<double>::stream(s, indent + "  ", v.yPos);
    s << indent << "orientation: ";
    Printer<double>::stream(s, indent + "  ", v.orientation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUGBOAT_CONTROL_MESSAGE_TUGWAYPOINT_H
