// Generated by gencpp from file tugboat_control/WaypointAvailableRequest.msg
// DO NOT EDIT!


#ifndef TUGBOAT_CONTROL_MESSAGE_WAYPOINTAVAILABLEREQUEST_H
#define TUGBOAT_CONTROL_MESSAGE_WAYPOINTAVAILABLEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tugboat_control/Waypoint.h>

namespace tugboat_control
{
template <class ContainerAllocator>
struct WaypointAvailableRequest_
{
  typedef WaypointAvailableRequest_<ContainerAllocator> Type;

  WaypointAvailableRequest_()
    : waypoint()  {
    }
  WaypointAvailableRequest_(const ContainerAllocator& _alloc)
    : waypoint(_alloc)  {
  (void)_alloc;
    }



   typedef  ::tugboat_control::Waypoint_<ContainerAllocator>  _waypoint_type;
  _waypoint_type waypoint;




  typedef boost::shared_ptr< ::tugboat_control::WaypointAvailableRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tugboat_control::WaypointAvailableRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointAvailableRequest_

typedef ::tugboat_control::WaypointAvailableRequest_<std::allocator<void> > WaypointAvailableRequest;

typedef boost::shared_ptr< ::tugboat_control::WaypointAvailableRequest > WaypointAvailableRequestPtr;
typedef boost::shared_ptr< ::tugboat_control::WaypointAvailableRequest const> WaypointAvailableRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tugboat_control::WaypointAvailableRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tugboat_control::WaypointAvailableRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tugboat_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'tugboat_control': ['/home/sondre/catkin_ws/src/tugboat_control/msg', '/home/sondre/catkin_ws/src/tugboat_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tugboat_control::WaypointAvailableRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tugboat_control::WaypointAvailableRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tugboat_control::WaypointAvailableRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tugboat_control::WaypointAvailableRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tugboat_control::WaypointAvailableRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tugboat_control::WaypointAvailableRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tugboat_control::WaypointAvailableRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9a1d86b9c7914a76bee33a409fcfe4da";
  }

  static const char* value(const ::tugboat_control::WaypointAvailableRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9a1d86b9c7914a76ULL;
  static const uint64_t static_value2 = 0xbee33a409fcfe4daULL;
};

template<class ContainerAllocator>
struct DataType< ::tugboat_control::WaypointAvailableRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tugboat_control/WaypointAvailableRequest";
  }

  static const char* value(const ::tugboat_control::WaypointAvailableRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tugboat_control::WaypointAvailableRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Waypoint waypoint\n\
\n\
================================================================================\n\
MSG: tugboat_control/Waypoint\n\
uint8 ID\n\
float64 x #	x position in meters\n\
float64 y #	y position in meters\n\
float64 v #	Velocity in m/s\n\
float64 o #	Orientation in +- pi radians from x-axis, for ship. Set outside scope to ignore Orientation\n\
";
  }

  static const char* value(const ::tugboat_control::WaypointAvailableRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tugboat_control::WaypointAvailableRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypoint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointAvailableRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tugboat_control::WaypointAvailableRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tugboat_control::WaypointAvailableRequest_<ContainerAllocator>& v)
  {
    s << indent << "waypoint: ";
    s << std::endl;
    Printer< ::tugboat_control::Waypoint_<ContainerAllocator> >::stream(s, indent + "  ", v.waypoint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUGBOAT_CONTROL_MESSAGE_WAYPOINTAVAILABLEREQUEST_H
