(cl:defpackage tugboat_control-msg
  (:use )
  (:export
   "<BOATPOSE>"
   "BOATPOSE"
   "<BOATPOSE>"
   "BOATPOSE"
   "<CLEARWAYPOINT>"
   "CLEARWAYPOINT"
   "<CLEARWAYPOINT>"
   "CLEARWAYPOINT"
   "<PUSHINGFORCE>"
   "PUSHINGFORCE"
   "<PUSHINGFORCE>"
   "PUSHINGFORCE"
   "<THRUST>"
   "THRUST"
   "<THRUST>"
   "THRUST"
   "<TUGSETPOINTS>"
   "TUGSETPOINTS"
   "<TUGSETPOINTS>"
   "TUGSETPOINTS"
   "<WAYPOINT>"
   "WAYPOINT"
   "<WAYPOINT>"
   "WAYPOINT"
  ))

