classdef TugSetpoints < robotics.ros.Message
    %TugSetpoints MATLAB implementation of tugboat_control/TugSetpoints
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'tugboat_control/TugSetpoints' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'c8ca54d2369480b1a8ddd3bbd0df223a' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Orientation
        PushingForce
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Orientation', 'PushingForce'} % List of non-constant message properties
        ROSPropertyList = {'orientation', 'pushingForce'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = TugSetpoints(msg)
            %TugSetpoints Construct the message object TugSetpoints
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function orientation = get.Orientation(obj)
            %get.Orientation Get the value for property Orientation
            orientation = double(obj.JavaMessage.getOrientation);
        end
        
        function set.Orientation(obj, orientation)
            %set.Orientation Set the value for property Orientation
            validateattributes(orientation, {'numeric'}, {'nonempty', 'scalar'}, 'TugSetpoints', 'Orientation');
            
            obj.JavaMessage.setOrientation(orientation);
        end
        
        function pushingforce = get.PushingForce(obj)
            %get.PushingForce Get the value for property PushingForce
            pushingforce = double(obj.JavaMessage.getPushingForce);
        end
        
        function set.PushingForce(obj, pushingforce)
            %set.PushingForce Set the value for property PushingForce
            validateattributes(pushingforce, {'numeric'}, {'nonempty', 'scalar'}, 'TugSetpoints', 'PushingForce');
            
            obj.JavaMessage.setPushingForce(pushingforce);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Orientation = obj.Orientation;
            cpObj.PushingForce = obj.PushingForce;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Orientation = strObj.Orientation;
            obj.PushingForce = strObj.PushingForce;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Orientation = obj.Orientation;
            strObj.PushingForce = obj.PushingForce;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.tugboat_control.TugSetpoints.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.tugboat_control.TugSetpoints;
            obj.reload(strObj);
        end
    end
end
