# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tugboat_control/WaypointAvailableRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import tugboat_control.msg

class WaypointAvailableRequest(genpy.Message):
  _md5sum = "9a1d86b9c7914a76bee33a409fcfe4da"
  _type = "tugboat_control/WaypointAvailableRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """Waypoint waypoint

================================================================================
MSG: tugboat_control/Waypoint
uint8 ID
float64 x #	x position in meters
float64 y #	y position in meters
float64 v #	Velocity in m/s
float64 o #	Orientation in +- pi radians from x-axis, for ship. Set outside scope to ignore Orientation"""
  __slots__ = ['waypoint']
  _slot_types = ['tugboat_control/Waypoint']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       waypoint

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WaypointAvailableRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.waypoint is None:
        self.waypoint = tugboat_control.msg.Waypoint()
    else:
      self.waypoint = tugboat_control.msg.Waypoint()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B4d().pack(_x.waypoint.ID, _x.waypoint.x, _x.waypoint.y, _x.waypoint.v, _x.waypoint.o))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.waypoint is None:
        self.waypoint = tugboat_control.msg.Waypoint()
      end = 0
      _x = self
      start = end
      end += 33
      (_x.waypoint.ID, _x.waypoint.x, _x.waypoint.y, _x.waypoint.v, _x.waypoint.o,) = _get_struct_B4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B4d().pack(_x.waypoint.ID, _x.waypoint.x, _x.waypoint.y, _x.waypoint.v, _x.waypoint.o))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.waypoint is None:
        self.waypoint = tugboat_control.msg.Waypoint()
      end = 0
      _x = self
      start = end
      end += 33
      (_x.waypoint.ID, _x.waypoint.x, _x.waypoint.y, _x.waypoint.v, _x.waypoint.o,) = _get_struct_B4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B4d = None
def _get_struct_B4d():
    global _struct_B4d
    if _struct_B4d is None:
        _struct_B4d = struct.Struct("<B4d")
    return _struct_B4d
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tugboat_control/WaypointAvailableResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class WaypointAvailableResponse(genpy.Message):
  _md5sum = "b2020b919eb112b1b4fe9db01673724e"
  _type = "tugboat_control/WaypointAvailableResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """std_msgs/Bool ans

================================================================================
MSG: std_msgs/Bool
bool data"""
  __slots__ = ['ans']
  _slot_types = ['std_msgs/Bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ans

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WaypointAvailableResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.ans is None:
        self.ans = std_msgs.msg.Bool()
    else:
      self.ans = std_msgs.msg.Bool()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_B().pack(self.ans.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.ans is None:
        self.ans = std_msgs.msg.Bool()
      end = 0
      start = end
      end += 1
      (self.ans.data,) = _get_struct_B().unpack(str[start:end])
      self.ans.data = bool(self.ans.data)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_get_struct_B().pack(self.ans.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.ans is None:
        self.ans = std_msgs.msg.Bool()
      end = 0
      start = end
      end += 1
      (self.ans.data,) = _get_struct_B().unpack(str[start:end])
      self.ans.data = bool(self.ans.data)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
class WaypointAvailable(object):
  _type          = 'tugboat_control/WaypointAvailable'
  _md5sum = 'e256e0c870845448cbf5d0a1d2ba0749'
  _request_class  = WaypointAvailableRequest
  _response_class = WaypointAvailableResponse
